name: Bandit Vulnerabilitie scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Check
       uses: jpetrucciani/bandit-check@master
       with:
        path: '-r ./src'
  



